### ISSUE TITLE
Trouble with ERA5-HRES 1979-2021 - resolution 0.25 

### ISSUE THREAD

**Issue by heliosCanlilar** [abhinavyesss/graphcast-predict#4]
Hi!

Great work on this repo! I wondered if you had an example for how to use the ERA5-HRES 1979-2021 - resolution 0.25 model instead of the 1.0 one. Do we need to change anything else besides the following line?:

`with open(r'model/params/GraphCast_operational - ERA5-HRES 1979-2021 - resolution 0.25 - pressure levels 13 - mesh 2to6 - precipitation output only.npz', 'rb') as model:`

**Comment by abhinavyesss** [comment]
You will have to make multiple changes.

1. Line 63, the step value of the range.
2. Line 64, the step value of the range.
3. Line 89, the appropriate model name. There is a chance the model working on 0.25 degree resolution only works with 39 pressure levels, in that case you will have to change the list of pressure level values too.
4. Line 186, the grid value should be 0.25/0.25.
5. Line 209, the grid value should be 0.25/0.25.

**Comment by heliosCanlilar** [comment]
Awesome thanks so much Abhinav! That's exactly what I needed.

**Comment by heliosCanlilar** [comment]
One follow up question for you. I noticed in the ECMWF documentation that
"daily updates for ERA5-Land-T are available about 5 days behind real
time". Do you know of a data source that has all the columns we need that's
updated more frequently? Ideally real time.

**Comment by abhinavyesss** [comment]
I don't, to be honest. The 5 day latency period is something that has troubled me too and I have been unable to find a solution. However, when I do, I will make sure to update it.

**Comment by ElNino9495** [comment]
Hi, I have been trying to modify this code to make predictions for the 0.25 resolution. I have made the following changes
Line 63, the step value of the range.
Line 64, the step value of the range.
Line 89, the appropriate model name. There is a chance the model working on 0.25 degree resolution only works with 39 pressure levels, in that case you will have to change the list of pressure level values too.
Line 186, the grid value should be 0.25/0.25.
Line 209, the grid value should be 0.25/0.25.
and used the model "/model/params/params-GraphCast_operational-ERA5-HRES_1979-2021-resolution_0.25-pressure_levels_13-mesh_2to6-precipitation_output_only.npz"

However when i try to make predictions I end up with this error:
ValueError: 'grid2mesh_gnn/ _networks_builder/encoder_nodes_grid_nodes_mlp//linear_0/w' with retrieved shape (184, 512) does not match shape=[186, 512] dtype=dtype(bfloat16)

Can you help me resolve this? @abhinavyesss @heliosCanlilar
